config/routes.rb
Consent::Application.routes.draw do

  resources :subscribers, only: [:new, :create]
  resources :contact_us
  resources :patients_testimonials
  resources :doctors_testimonials
  resources :report_questions, :only => [:new, :create, :destroy]

  match "report_questions/reply",:to => "report_questions#reply",:via=> [:get]
  match ":id/report_questions",:to => "report_questions#index",:as=>:report_questions,:via=> [:get]

  match "report_questions/:id",:to => "report_menus#show",:as=>:report_question,:via=> [:get]

  match ":id/report_questions",:to => "report_questions#create",:as=>:report_questions,:via=> [:post]

  authenticated :doctor do
    root :to => 'patients#index'
  end

  match "/admin/active_doctors" => 'admin/doctors#active_doctors', via: :get, as: "active_doctors"
  match "/admin/non-active-doctors" => 'admin/doctors#non_active_doctors', via: :get, as: "non_active_doctors"
  match "/admin/cancel-trial/:id" => 'admin/doctors#admin_cancel_trials', via: :get, as: "admin_cancel_trials"

  authenticated :patient do
    root :to => 'patients#patient_info'
  end

  root :to => "home#index"

  match '/patients/get_emails', :to => "patients#get_emails", :as => :get_emails
  resources :patients
  devise_for :patients, :controllers => { :sessions => "sessions"}, :path => "patient", :path_names => { :sign_in => "login" } do
    match '/patients/signin/:token', :to => 'sessions#new', :as => 'signin_patient', :via => [:get]
  end

  resources :report_menus,:only => [ :create, :new, :update, :edit ]
  match '/report_menus/new/:id' , :to => 'report_menus#new' ,:as => :new_report,:via => [ :get ]

  match "embeddocusign/create" =>"embeddocusign#create", :as => :embeddocusign_create

  resources :videos, :only => [:index, :show]

  resources :user_steps
  get "doctor_profile/index"
  get "doctor_profile/edit"
  get "doctor_profile/update"
  get "patient_report/new"
  get "patient_report/create"

  get '/report/download_as_pdf/:id',:to =>"reports#download_as_pdf",:as=> :download_as_pdf

  match '/update_consent_report/:id' => "patients#update_consent_report", :as => :update_consent_report

  resources :patient_report
  match 'patient_report/new', :controller => 'patient_report', :action => 'create', :as => :report_for_patient
  match 'profile' => "doctor_profile#edit", :as => :profile
  match 'profile/edit' => "doctor_profile#update", :via => [ :put ], :as => :update_profile
  match "/doctor/cancel-trial/:id" => 'doctor_profile#doctor_cancel_trials', via: :get, as: "doctor_cancel_trials"

  match 'patient/patient_info' => "patient#patient_info", :via => [ :get ]
  match '/consent_report/:id' => "patients#consent_report",:as => :consent_report
  match '/create_report/:id' => "patients#create_report", :as => :create_report
  match '/edit_consent_report/:id' => "patients#edit_consent_report", :as => :edit_consent_report
  match '/patients/show_code', :to => "patients#show_code", :as => :show_code
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan

  match '/reports/access_report', :to => "reports#access_report", :as => :access_report
  match '/reports/access_rep/:id', :to => "reports#access_rep", :as => :access_rep
  match '/reports/show_report', :to => "reports#show_report" , :as => :show_report
  match ':id/login_page', :to => "reports#login_page" , :as => :login_page
  match '/reports/send_mail/:id', :to => "reports#send_mail", :as => :send_mail
  match '/reports/past_report',:to => "reports#past_report", :as => :past_report
  match '/reports/view_report/:id',:to => "reports#view_report",:as => :view_report
  match '/reports/:id/website_desclaimer',:to =>"reports#website_desclaimer",:as=> :website_desclaimer
  get '/reports/:id/pat_report',:to =>"reports#pat_report",:as=> :pat_report

  get '/reports/signature_created_msg',:to=>"reports#signature_created_msg",:as=> :signature_created_msg
  match '/:id/edit' => "confirm_detail#edit", :as => :edit
  match '/update/:id' => "confirm_detail#update", :as => :update
  match '/show/:id' => "confirm_detail#show",:as => :show

  match '/reports/:id/i_do_not_agree', :to => "reports#i_do_not_agree", :as => :i_do_not_agree
  match '/patient/patient_update' => "patient#pat_update", :as => :pat_update
  match 'home/terms_condition' => "home#terms_condition"

  resources :payments, :only => [:new,  :create]
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/select_plan', :to => 'payments#select_plan', :as => 'select_plan'
  match '/payments/plan_detail', :to => 'payments#plan_detail', :as => 'plan_detail'
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan
  post 'payments/webhook'

  resources :photos

  get '/home/coming_soon',:to =>'home#coming_soon'
  get '/home/contact_us',:to =>'home#contact_us'

  match '/home/services' =>'home#services', :as => :services
  match '/home/about_us' =>'home#about_us', :as => :about_us
  match '/home/contact_us' =>'home#contact_us', :as => :contact_us
  match '/home/contact_us_submit', :to => "home#contact_us_submit", :as => :contact_us_submit
  match '/home/how_it_works' =>'home#how_it_works', :as => :how_it_works

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :doctors, :controllers => { :registrations => "registrations", :sessions => "sessions",:passwords => "passwords" } do
     get '/doctors/sign_out' => 'devise/sessions#destroy'
     get '/doctors/sign_in' => 'devise/sessions#new'
  end

    match "embeddocusign/create_template" =>"embeddocusign#create_template", :as => :embeddocusign_create_template
    match "embeddocusign/create_envelope_from_template" =>"embeddocusign#create_envelope_from_template", :as => :create_envelope_from_template
    match "embeddocusign/create_env_from_doc/:id" =>"embeddocusign#create_env_from_doc", :as => :create_env_from_doc
    match "embeddocusign/generate_pdf/:id" =>"embeddocusign#generate_pdf", :as => :generate_pdf

  namespace "admin" do
    resources :doctors do
      get :pat_show
    end
    resources :patients do
      get :show_patient_reports
    end
    resources :procedures do
      get :procedure_show_type
    end
    resources :procedure_types do
      get :sub_type
    end
  end

  namespace "admin" do
    resources :videos do
      post :change_procedure
      new do
        post :upload
        get  :save_video
      end
    end
    resources :photos
  end

  match '/admin/videos/change_procedure', :to => "admin/videos#change_procedure"
  match '/admin/procedure_types/:id/create_subtype', :to => "admin/procedure_types#create_subtype" ,:as => 'create_subtype'

  match 'signature_pads/:id' => "signature_pads#open_form", :as => :open_form
  match 'send_mail/:id' => "signature_pads#send_mail", :as => :send_mail_pad

  match  'report/signature_create/:id'=> "reports#signature_create", :as => :signature_create
  match '/signatures/:id' => "reports#sig_create",:as => :sig_create
  match '/thnkyou_msg' => "reports#thnkyou_msg",:as => :thnkyou_msg

 if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  ActiveAdmin.routes(self)
end

app/views/layouts/shared/_contact_us.html.erb
<article id="content" class="cols-b">
  <nav id="breadcrumbs">
    <ol>
      <li><a href="default.htm">Home</a></li>
      <li>Contact us</li>
    </ol>
  </nav>
  <div class="map-a">
    <header class="vcard">
      <h2 class="fn org">eInformedConsent</h2>
      <p class="adr"><span class="street-address">841 Lorem Ipsum Dolor St.</span> <span class="locality">Queensland</span>, <span class="country-name">Australia</span></p>
      <ul>
        <li class="tel">+1 123 123 1233</li>
        <li><a class="email">info//medical/com</a></li>
      </ul>
    </header>
    <p class="scheme-a">Lorem ipsum medical center</p>
    <figure><img src="images/map-a.png" alt="Placeholder" width="660" height="469"></figure>
  </div>
  <aside>
    <form onSubmit="return submitForm();" action="" method="post" class="contactform" name="homefrm1" id="contact">
      <input type="hidden"  name="event" value="start" />
      <fieldset>
        <legend>Send us a message</legend>
        <p>
          <label for="ca">Your name</label>
          <input type="text" id="ca" name="name" required>
        </p>
        <p>
          <label for="cb">Email address</label>
          <input type="email" id="cb" name="email" required>
        </p>
        <p class="select-b">
          <label for="cc">Subject</label>
          <input name="subject" type="text" id="cd" required>
        </p>
        <p>
          <label for="cd">Message</label>
          <textarea id="cc" name="msg" required></textarea>
        </p>
        <p><button type="submit">Submit</button></p>
      </fieldset>
    </form>
    <div id="alert">
      <div class="message"></div>
    </div>
  </aside>
</article>

app/views/layouts/shared/_flash_message.html.erb
<% flash.each do |key, msg| %>
	<div align="center" class="row reg-success-select-plan alert alert-<%= key %>">
	  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	  <%= msg %>
	</div>
<% end %>

app/views/layouts/shared/_footer_css.html.erb
<style type="text/css">
    * {
    margin: 0;
  }
  html, body {
    height: 100%;
  }
  .page-wrap {
    min-height: 100%;
    /* equal to footer height */
    margin-bottom: -95px;
  }
  .page-wrap:after {
    content: "";
    display: block;
  }
  .site-footer{
    float: left;
    width: 100%;
  }
  .site-footer, .page-wrap:after {
    /* .push must be the same height as footer */
    height: 95px;
  }
</style>

app/views/layouts/shared/_front_page_menu.html.erb
<div class="row">
  <div class="container">
    <div class="bs-example">
      <nav role="navigation" class="navbar navbar-default">
        <div class="navbar-header">
          <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">      
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">Menu</a> 
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
           <li class="<%= 'active' if current_page?(root_url) %>"><a href="<%= root_url%>">Home</a></li>
            <li class="<%= 'active' if current_page?(how_it_works_path) %>"><a href="<%= how_it_works_path%>">How it works</a></li>
            <li class="<%= 'active' if current_page?(services_path) %>"><a href="<%= services_path%>">SERVICES/BENEFITS</a></li>
            <li class="<%= 'active' if current_page?(plan_detail_path) %>"><a href="<%= plan_detail_path%>">Subscription Plans</a></li>
            <li class="<%= 'active' if current_page?(about_us_path) %>"><a href="<%= about_us_path%>">About Us</a></li>
            <li class="<%= 'active' if current_page?(contact_us_path) %>"><a href="<%= contact_us_path%>">Contact Us</a></li>
            <li class="pre_link"><a data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">presentation-menu</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/shared/_frontpage_getinvolved.html.erb
<div>
  <h3>Get Involved</h3>
  <ul>
    <li><a href="default.htm">Appointments</a></li>
    <li><a href="default.htm">Billing &amp; Insurance</a></li>
    <li><a href="default.htm">Find a Doctor</a></li>
    <li><a href="default.htm">Maps &amp; Directions</a></li>
  </ul>
</div>

app/views/layouts/shared/_frontpage_header.html.erb
<div class="row">
  <div class="container header_wrap">
    <%= render "/layouts/shared/front_page_logo"%>
    <div class="col-lg-8  header_contact" align="right">
      <span>
        <img src="/assets/email_icon.png" alt="">
        <a href="mailto:info@einformedconsent.com">info@einformedconsent.com</a>
      </span>
      <div class="header_btns">
        <a href="#" data-toggle="modal" data-target="#myModal" class="blue_btn">Doctor Login</a>
        <a href="<%= new_doctor_registration_path%>" class="blue_btn" onclick="deleteAllCookie(['free_plan', 'subscribed_to'])">Subscribe Here</a>
      </div>
    </div>
    <div class="row" align="center">
      <div class="col-xs-12">
        <div class="video-btn-hr text-center">
          <a href="#" class="howItWorkBtn" data-toggle="modal" data-target="#videoModal" data-theVideo="http://tpstracker.com/demo/einformedconsent/video_V2.mp4" data-backdrop="static">
            <span class="glyphicon glyphicon-facetime-video"></span>
            How it works
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "/layouts/shared/front_page_menu"%>

<%= render :template => "devise/sessions/new",:locals => {:resource => current_doctor,:resource_name => :doctor } %>

<%= render :template => "devise/passwords/new",:locals => {:resource => current_doctor,:resource_name => :doctor } %>

app/views/layouts/shared/_frontpage_your_visit.html.erb
<div>
  <h3>Your Visit</h3>
  <ul>
    <li><a href="default.htm">Appointments</a></li>
    <li><a href="default.htm">Billing &amp; Insurance</a></li>
    <li><a href="default.htm">Find a Doctor</a></li>
    <li><a href="default.htm">Maps &amp; Directions</a></li>
  </ul>
</div>

app/views/layouts/shared/_header.html.erb
<div class="row user_header_wrap">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" align="right">
      <% if doctor_signed_in? %>

        <div class="col-lg-4 col-md-4 col-sm-4" align="center">
          <a href="/">
            <img src="/assets/logo.png" alt="" class="img-responsive">
          </a>
        </div>
        <div class="col-lg-8  header_contact" align="right">
          <span>
            <img src="/assets/email_icon.png" alt="">
            <a href="mailto:info@einformedconsent.com">info@einformedconsent.com</a>
          </span>
          <div class="header_btns">
            Dr. <%= current_doctor.doctor_name%>&nbsp;&nbsp;| &nbsp;&nbsp;<%= link_to "Logout",destroy_doctor_session_path%>
          </div>
        </div>
      <% else %>
        <%# if session[:patient_id].present? %>
        <img src="/assets/logo.png" alt="" class="img-responsive">
        <%# else %>
        <%# end %>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/shared/_login_jquery.html.erb
<script type="text/javascript">

  (function($){

      var timeout = 600000;
      // var timeout = 2000;

      $(document).bind("idle.idleTimer", function(){
         $('.my_main').html("<%= escape_javascript(render :partial => '/layouts/shared/timeout').html_safe %>");
         $('.ajax').html("<%= escape_javascript(render :partial => '/report_questions/blank').html_safe %>");
         $.get("/doctors/sign_out","","","scripts")
         window.history.pushState("", "", '/');
      });

      // $(document).bind("active.idleTimer", function(){
      //      console.log("active");
      // });

      $.idleTimer(timeout);

  })(jQuery);

</script>

app/views/layouts/shared/_menu.html.erb
<% if doctor_signed_in? %>
<div class="row user_sub_header">
  <div class="container">
    <div class="col-lg-4 col-md-3 col-sm-6 col-xs-12 sub_header_left" align="center">
      <% @fullname = [] %>
      <% @name = current_doctor.doctor_name.split(" ") %>
      <% @name.each do |name| %>
        <% @fullname << name.titleize %>
      <% end %>

      <span><%= @fullname.join(" ") %></span>
      <p>
        <% @speciality= Speciality.all %>
          <% @speciality.each do |s| %>
            <% if current_doctor.speciality_id == s.id %>
              <%= s.spe_name.titleize %>
            <% end %>
          <% end %>
          <br><br>
          <% @add = current_doctor.address.titleize %>
          <% @b = @add.split(" ,") %>
          <% @c= @b.join(",") %>
          <% @d = @c.split(", ") %>
          <%= @d.join(",") %>

          <br>
          <%= current_doctor.city.titleize %>,<%= current_doctor.state.titleize %> <%= current_doctor.zip %><br>
          <%= current_doctor.phone %><br>
      </p>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-6 col-xs-12 add_new_consent_wrap" align="center">
      <a href="<%=patient_report_new_path%>">
        <img src="/assets/add_new_consent.png" alt="" class="img-responsive">
      </a>
    </div>
    <div class="clearfix clear_hide"></div>
      <div class="dashboard_menu_wrap">
        <%= link_to patients_path,:class=>(current_page?(patients_path) == true ? "col-lg-1 col-md-1 col-sm-3 col-xs-6 dashboard_menu_active" : "col-lg-1 col-md-1 col-sm-3 col-xs-6")  do %>
          <div align="center">
            <% if current_page?(patients_path) == true  %>
              <img src="/assets/my_patients_active.png" alt="">
            <%elsif current_page?(patients_path) == false%>
              <img src="/assets/my_patients_normal.png" alt="">
            <%end%>
          </div>
          <p><b>My Patients</b></p>
        <%end%>
        <%= link_to doctor_profile_index_path,:class=>(current_page?(doctor_profile_index_path) == true ? "col-lg-1 col-md-1 col-sm-3 col-xs-6 dashboard_menu_active" : "col-lg-1 col-md-1 col-sm-3 col-xs-6") ,:"data-toggle"=>"modal",:"data-target"=>"#porfile_view" do %>
          <div align="center">
            <% if current_page?(doctor_profile_index_path) == true  %>
              <img src="/assets/my_profile_active.png" alt="">
            <%elsif current_page?(doctor_profile_index_path) == false%>
              <img src="/assets/my_profile_normal.png" alt="">
            <%end%>
          </div>
          <p><b>My Profile</b></p>
        <%end%>
        <%= link_to doctor_plan_path,:class=>(current_page?(doctor_plan_path) == true ? "col-lg-1 col-md-1 col-sm-3 col-xs-6 dashboard_menu_active" : "col-lg-1 col-md-1 col-sm-3 col-xs-6")  do %>
          <div align="center">
            <% if current_page?(doctor_plan_path) == true  %>
              <img src="/assets/subscription_active.png" alt="">
            <%elsif current_page?(doctor_plan_path) == false%>
              <img src="/assets/subscription_normal.png" alt="">
            <%end%>
          </div>
          <p><b>Subscribe</b></p>
        <%end%>
        <%= link_to past_report_path,:class=>(current_page?(past_report_path) == true ? "col-lg-1 col-md-1 col-sm-3 col-xs-6 dashboard_menu_active" : "col-lg-1 col-md-1 col-sm-3 col-xs-6") do %>
          <div align="center">
            <% if current_page?(past_report_path) == true  %>
              <img src="/assets/past_reports_active.png" alt="">
            <%elsif current_page?(past_report_path) == false%>
              <img src="/assets/past_reports_normal.png" alt="">
            <%end%>
          </div>
          <p><b>Past Reports</b></p>
        <%end%>
     </div>
  </div>
</div>
<div class="modal fade" id="porfile_view" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<% else %>

  <% @pat_doc_id = ""%>
  <% @doc_spe_id = ""%>
  <% @session_id %>
  <% @patients = Patient.all %>
  <% @doctors = Doctor.all %>
  <% @speciality = Speciality.all %>

  <% @patients.each do |p|  %>
    <% if p.first_name == session[:patient_id] %>
      <% @pat_doc_id = p.doctor_id %>
      <% @session_id =  p.doctor_id %>
    <% end %>
  <% end %>
    <% @fullname = [] %>
    <% session[:patient_id] %>
    <div class="row user_sub_header">
      <div class="container">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 sub_header_left" align="center">
            <% @doctors.each do |d| %>
              <% if d.id == @pat_doc_id%>
                <% @name = d.doctor_name.split(" ") %>
                <% @name.each do |name| %>
                  <% @fullname<<name.titleize %>
                <% end %>
                <span>Dr. <%= @fullname.join(" ") %></span><br><br>
                <% @doc_spe_id = d.speciality_id %>
              <% end %>
            <% end %>
            <p>
            <% @doctors.each do |d| %>
              <% if d.id == @pat_doc_id%>
                Contact : <%= d.phone %><br>
              <% end %>
            <% end %>
            </p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 sub_header_right" align="center">
          <% @doctors.each do |d| %>
            <% if d.id == @pat_doc_id%>
              <span>Location</span>
              <p>
                <% @add = d.address.titleize %>
                <% @b = @add.split(" ,") %>
                <% @c= @b.join(",") %>
                <% @d = @c.split(", ") %>
                <%= @d.join(",") %>
                <br>
              <%= d.city.titleize %> <%= d.state.titleize %><br>
              <%= d.zip %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/shared/_patient_login_screen.html.erb
<div class="row user_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="patient_login_box">
        <h1>Patient Login</h1>
        <p>Please Enter Patient Passcode provided<br>by Your Doctor.</p>
        <%= form_for :report, :url => access_report_path, :method => 'POST',:class=>"form" do %>
          <div class="form-group form_wrap">
            <%= text_field_tag :report_code,"",:class=>"form-control",:placeholder=>"Enter Patient Passcode Here"  %>
          </div>
          <div class="form-group form_wrap">
            <input type="button" class="form-control pull-left login_leave_btn" value="Leave" onclick="window.location='http://www.einformedconsent.com/'">
            <%= submit_tag "Go",:class=>"form-control pull-right login_go_btn"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_presentation_modal.html.erb
<!-- Modal -->
<div id="consentModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="blue_btn pull-right" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_seo_header.html.erb
<%if params[:controller] == "home" && params[:action] == "index"%>
  <title>eInformed Consent</title>
  <meta name="description" content="A subscription based informed consent consisting of a customized video presentation, which describes for the patient the proposed dental implant procedure.">
<% elsif params[:controller] == "registrations" && params[:action] == "new" %>
  <title>eInformedConsent</title>
  <meta name="description" content="Reduce dental implant litigation risk. Subscribe to create and email proposed dental implant treatment consent presentations. ">
<% elsif params[:controller] == "home" && params[:action] == "about_us" %>
  <title>eInformed Consent</title>
  <meta name="description" content="How to provide quality dental implant services, reduce patient misunderstandings and meet legal consent requirements while reducing practice resources.  ">
<% elsif params[:controller] == "home" && params[:action] == "contact_us" %>
  <title>eInformed Consent</title>
  <meta name="description" content="Do you have a question regarding how to present dental implant related treatments to patients?  Please do not hesitate to contact us.">
<% elsif params[:controller] == "home" && params[:action] == "how_it_works" %>
  <title>eInformed Consent</title>
  <meta name="description" content="You get a 5-minute video training on how the system works to reduce your exposure to dental implant related lawsuits..  ">
<% elsif params[:controller] == "home" && params[:action] == "services" %>
  <title>eInformed Consent</title>
  <meta name="description" content="Find what equipment patients can use..  Understand consent presentations - alternative treatment, sedation, proposed treatment and possible complications.">
<% else %>
<title>eInformed Consent</title>
<meta name="description" content="A subscription based informed consent consisting of a customized video presentation, which describes for the patient the proposed dental implant procedure.">
<% end %>

app/views/layouts/shared/_topheader_menu.html.erb
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <% if doctor_signed_in? %>
      <li class="li-first"><span class="text">Dr. <%= current_doctor.doctor_name%></span></li>
      <li><%= link_to raw("<i class='icon icon-user'></i> <span class='text'>Profile</span>"),doctor_profile_index_path%></li>
      <li><%= link_to raw("<i class='icon icon-share-alt'></i><span class='text'>Sign out</span>"),destroy_doctor_session_path%></li>
    <% elsif patient_signed_in? %>
    <li class="li-first-patient">
      Welcome <%= current_patient.first_name%> <%= current_patient.last_name %></li>
      </span></a></li> <li class="" ><a title="" href="#"><i class="icon icon-user"></i> <span class="text">Profile</span></a></li>
      <li><%= link_to raw("<i class='icon icon-share-alt'></i><span class='text'>Sign out</span>"),destroy_patient_session_path,:method => :delete%></li>

    <%end%>
  </ul>
</div>
<% if doctor_signed_in? %>
<div id="search">
  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-left" title="Search"><i class="icon-search icon-white"></i></button>
</div>
<% elsif patient_signed_in? %>

<%end%>
<!--close-top-Header-menu-->

<!-- style="border-left:1px solid #fff; margin: 3px 20px 0 42px;" -->