config/routes.rb
Consent::Application.routes.draw do

  resources :subscribers, only: [:new, :create]
  resources :contact_us
  resources :patients_testimonials
  resources :doctors_testimonials
  resources :report_questions, :only => [:new, :create, :destroy]

  match "report_questions/reply",:to => "report_questions#reply",:via=> [:get]
  match ":id/report_questions",:to => "report_questions#index",:as=>:report_questions,:via=> [:get]

  match "report_questions/:id",:to => "report_menus#show",:as=>:report_question,:via=> [:get]

  match ":id/report_questions",:to => "report_questions#create",:as=>:report_questions,:via=> [:post]

  authenticated :doctor do
    root :to => 'patients#index'
  end

  match "/admin/active_doctors" => 'admin/doctors#active_doctors', via: :get, as: "active_doctors"
  match "/admin/non-active-doctors" => 'admin/doctors#non_active_doctors', via: :get, as: "non_active_doctors"
  match "/admin/cancel-trial/:id" => 'admin/doctors#admin_cancel_trials', via: :get, as: "admin_cancel_trials"

  authenticated :patient do
    root :to => 'patients#patient_info'
  end

  root :to => "home#index"

  match '/patients/get_emails', :to => "patients#get_emails", :as => :get_emails
  resources :patients
  devise_for :patients, :controllers => { :sessions => "sessions"}, :path => "patient", :path_names => { :sign_in => "login" } do
    match '/patients/signin/:token', :to => 'sessions#new', :as => 'signin_patient', :via => [:get]
  end

  resources :report_menus,:only => [ :create, :new, :update, :edit ]
  match '/report_menus/new/:id' , :to => 'report_menus#new' ,:as => :new_report,:via => [ :get ]

  match "embeddocusign/create" =>"embeddocusign#create", :as => :embeddocusign_create

  resources :videos, :only => [:index, :show]

  resources :user_steps
  get "doctor_profile/index"
  get "doctor_profile/edit"
  get "doctor_profile/update"
  get "patient_report/new"
  get "patient_report/create"

  get '/report/download_as_pdf/:id',:to =>"reports#download_as_pdf",:as=> :download_as_pdf

  match '/update_consent_report/:id' => "patients#update_consent_report", :as => :update_consent_report

  resources :patient_report
  match 'patient_report/new', :controller => 'patient_report', :action => 'create', :as => :report_for_patient
  match 'profile' => "doctor_profile#edit", :as => :profile
  match 'profile/edit' => "doctor_profile#update", :via => [ :put ], :as => :update_profile
  match "/doctor/cancel-trial/:id" => 'doctor_profile#doctor_cancel_trials', via: :get, as: "doctor_cancel_trials"

  match 'patient/patient_info' => "patient#patient_info", :via => [ :get ]
  match '/consent_report/:id' => "patients#consent_report",:as => :consent_report
  match '/create_report/:id' => "patients#create_report", :as => :create_report
  match '/edit_consent_report/:id' => "patients#edit_consent_report", :as => :edit_consent_report
  match '/patients/show_code', :to => "patients#show_code", :as => :show_code
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan

  match '/reports/access_report', :to => "reports#access_report", :as => :access_report
  match '/reports/access_rep/:id', :to => "reports#access_rep", :as => :access_rep
  match '/reports/show_report', :to => "reports#show_report" , :as => :show_report
  match ':id/login_page', :to => "reports#login_page" , :as => :login_page
  match '/reports/send_mail/:id', :to => "reports#send_mail", :as => :send_mail
  match '/reports/past_report',:to => "reports#past_report", :as => :past_report
  match '/reports/view_report/:id',:to => "reports#view_report",:as => :view_report
  match '/reports/:id/website_desclaimer',:to =>"reports#website_desclaimer",:as=> :website_desclaimer
  get '/reports/:id/pat_report',:to =>"reports#pat_report",:as=> :pat_report

  get '/reports/signature_created_msg',:to=>"reports#signature_created_msg",:as=> :signature_created_msg
  match '/:id/edit' => "confirm_detail#edit", :as => :edit
  match '/update/:id' => "confirm_detail#update", :as => :update
  match '/show/:id' => "confirm_detail#show",:as => :show

  match '/reports/:id/i_do_not_agree', :to => "reports#i_do_not_agree", :as => :i_do_not_agree
  match '/patient/patient_update' => "patient#pat_update", :as => :pat_update
  match 'home/terms_condition' => "home#terms_condition"

  resources :payments, :only => [:new,  :create]
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/select_plan', :to => 'payments#select_plan', :as => 'select_plan'
  match '/payments/plan_detail', :to => 'payments#plan_detail', :as => 'plan_detail'
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan
  post 'payments/webhook'

  resources :photos

  get '/home/coming_soon',:to =>'home#coming_soon'
  get '/home/contact_us',:to =>'home#contact_us'

  match '/home/services' =>'home#services', :as => :services
  match '/home/about_us' =>'home#about_us', :as => :about_us
  match '/home/contact_us' =>'home#contact_us', :as => :contact_us
  match '/home/contact_us_submit', :to => "home#contact_us_submit", :as => :contact_us_submit
  match '/home/how_it_works' =>'home#how_it_works', :as => :how_it_works

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :doctors, :controllers => { :registrations => "registrations", :sessions => "sessions",:passwords => "passwords" } do
     get '/doctors/sign_out' => 'devise/sessions#destroy'
     get '/doctors/sign_in' => 'devise/sessions#new'
  end

    match "embeddocusign/create_template" =>"embeddocusign#create_template", :as => :embeddocusign_create_template
    match "embeddocusign/create_envelope_from_template" =>"embeddocusign#create_envelope_from_template", :as => :create_envelope_from_template
    match "embeddocusign/create_env_from_doc/:id" =>"embeddocusign#create_env_from_doc", :as => :create_env_from_doc
    match "embeddocusign/generate_pdf/:id" =>"embeddocusign#generate_pdf", :as => :generate_pdf

  namespace "admin" do
    resources :doctors do
      get :pat_show
    end
    resources :patients do
      get :show_patient_reports
    end
    resources :procedures do
      get :procedure_show_type
    end
    resources :procedure_types do
      get :sub_type
    end
  end

  namespace "admin" do
    resources :videos do
      post :change_procedure
      new do
        post :upload
        get  :save_video
      end
    end
    resources :photos
  end

  match '/admin/videos/change_procedure', :to => "admin/videos#change_procedure"
  match '/admin/procedure_types/:id/create_subtype', :to => "admin/procedure_types#create_subtype" ,:as => 'create_subtype'

  match 'signature_pads/:id' => "signature_pads#open_form", :as => :open_form
  match 'send_mail/:id' => "signature_pads#send_mail", :as => :send_mail_pad

  match  'report/signature_create/:id'=> "reports#signature_create", :as => :signature_create
  match '/signatures/:id' => "reports#sig_create",:as => :sig_create
  match '/thnkyou_msg' => "reports#thnkyou_msg",:as => :thnkyou_msg

 if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  ActiveAdmin.routes(self)
end

app/controllers/patient_report_controller.rb
class PatientReportController < ApplicationController
  before_filter :authenticate_doctor!
  def new
    @procedures = Procedure.all
    @patient_report = current_doctor.patients.new
    @speciality_wise_procedure = current_doctor.speciality.procedures

  end


  def create
    @procedures = Procedure.all
    @procedure_type = ProcedureType.all
    if params[:existing_patient].present?
      @patient_report = params[:existing_patient]
      session[:patient_report] = @patient_report

    else
      @patient_report = current_doctor.patients.new(params[:patient])
      @speciality_wise_procedure = current_doctor.speciality.procedures
      # @demo = !@patient_report.errors.any?
      #  puts "-------------------------#{@patient_report.id}---------------------------------------------------------"
      # @patient_cnt = 0
      # current_doctor.patients.each do |patient|
      #   if patient.email == @patient_report.email

      #     @patient_cnt = 1
      #   end
      # end
      respond_to do |format|
        # if @patient_cnt == 0
          if @patient_report.save
            session[:patient_report] = @patient_report.id
            @patient_report.update_attributes(:correct_first_name => @patient_report.first_name,:correct_email => @patient_report.email,:correct_last_name => @patient_report.last_name)
            @patient_report.update_attributes(:correct_city => @patient_report.city,:correct_state => @patient_report.state,:correct_country => @patient_report.country)
            @patient_report.update_attributes(:correct_address => @patient_report.address,:correct_zip=>@patient_report.zip)
            @patient_report.update_attributes(:correct_phone_number=>@patient_report.phone_number,:correct_birthdate => @patient_report.birthdate)
            @patient_report.update_attributes(:correct_gender_number=>@patient_report.gender)

            # format.html { redirect_to root_url,notice: 'Patient was successfully created.' }
            format.js
            format.json #{render json: @patient_report, status: :created, location: @patient_report }
          else
            format.js
            # format.html { render "new" }
            format.json { render json: @patient_report.errors, status: :unprocessable_entity }
          end
        # else
        #   puts "already taken"
        #   format.html { redirect_to patients_path,notice: 'Patient was already created.' }
        #   format.js {flash[:notice]='Patient was already created.'}
        # end
      end
    end
  end

  def edit
    @patient_report = Patient.find(session[:patient_report])
  end

  def update
    @patient_report = Patient.find(session[:patient_report])
    @procedures = Procedure.all
    @procedure_type = ProcedureType.all

    respond_to do |format|
      if @patient_report.update_attributes(params[:patient])
        format.js #update.js.erb
      else
        format.js
      end
    end
  end

end

app/views/patient_report/_edit_patient_report.html.erb
<script type="text/javascript">
<%@patients = current_doctor.patients.all %>

$(document).ready(function(){
  var x = $("#fname").val();
  $("#fname").blur(function(){
      var y = $("#fname").val();
      $(".symbol").removeClass('email_taken_no');
      $(".e_msg").hide();
      <% @patients.each do |value| %>
        if(x == y)
        {

        }
        else if(y == "<%=value.email%>")
        {
          $(".symbol").addClass('email_taken_no');
          $(".e_msg").show();
          $("#fname").focus();
        }
      <% end %>
    });
});

$(document).ready(function(){
  if($('#dp6').length > 0)
  {
    $('#dp6').datepicker()
      .on('changeDate', function(ev){
        $('#dp6').datepicker('hide');
    });
  }
});
</script>

<style>
  .email_taken_no{
    content: url(/assets/email_taken.png);
  }
</style>

<div class="tab2">
  <div class="add-concent" >
    <div id="tabs">
      <div class="bs-example bs-example-tabs presentation_tabs_wrap">
        <ul class="nav nav-tabs custom_tabs" id="myTab">
          <li class="active col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#add_patient">1. Add Patient</a></li>
          <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#select_menu">2. Select Presentation Segment</a></li>
          <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#create_code">3. Create patient Code and Send</a></li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div id="add_patient" class="tab-pane fade active in tab_content">
            <div class="row tab_form">
              <div class="tab-background">
                <%= form_for patient_report , :as => :patient, :url => patient_report_path,  :remote => true,:html => { :method => :put,:multipart => true}  do |f| %>
                  <div class="add-concent-form">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                      <div class="form-group form_wrap">
                        <label for="fname">First name <em>*</em></label>
                        <%= f.text_field :first_name , :placeholder => "First Name" , :class => "form-control"%>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="fname">Last name <em>*</em></label>
                        <%= f.text_field :last_name , :placeholder => "Last Name", :class => "form-control" %>
                      </div>
                      <div class="row">
                        <div class="form-group form_wrap">
                          <label for="Gender">Gender <em>*</em></label>
                          <div class="row">
                            <div class="col-lg-2" style="padding-left:0;">
                              <div class="radio">
                                <label>
                                  <%=f.radio_button :gender , "Male"%>Male
                                </label>
                              </div>
                            </div>
                            <div class="col-lg-2" style="padding-left:0;">
                              <div class="radio">
                                <label>
                                 <%=f.radio_button :gender, "Female"%>Female
                                </label>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="email">Email <em>*</em></label>
                        <%= f.email_field :email,:placeholder => "Email", :class => "form-control",:id=>"fname" %>
                        <span class="symbol" style="margin-bottom:-8px;"> </span>
                        <span class="e_msg" style="display:none;  color:#ff0000;">This patient is already in your list.</span>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="email">Phone <em>*</em></label>
                        <%= f.hidden_field :phone_code,:placeholder => "Code", :class => "code"%>
                        <%= f.text_field :phone_number,:placeholder => "Number", :class => "form-control"%>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="bday">Birthdate <em>*</em></label>
                         <%= f.text_field :birthdate,:placeholder => "Enter Date of Birth", :id => "dp6" ,:class=>"form-control",:"data-date"=>"07/22/2013",:"data-date-format"=>"dd/mm/yyyy"%>
                      </div>
                     </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                      <div class="form-group form_wrap">
                        <label for="email">Address / suite<em>*</em></label>
                        <%= f.text_area :address, :placeholder => "Address",:class => "form-control",:rows => 5, :cols => 50  %>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="bday">City <em>*</em></label>
                         <%= f.text_field :city, :placeholder => "City", :class => "form-control" %>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="bday">State <em>*</em></label>
                        <%= f.text_field :state,:placeholder => "State", :class => "form-control" %>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="bday">Country <em>*</em></label>
                        <%= f.country_select :country,{priority: %w(US)}, :placeholder => "Country",:class=>"form-control"%>
                      </div>
                      <div class="form-group form_wrap">
                        <label for="bday">Zip <em>*</em></label>
                        <%= f.text_field :zip, :placeholder => "Zip", :class => "form-control" %>
                      </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                      <div class="col-lg-12 form_devider" align="center">
                        <img src="/assets/or_img.png" class="img-responsive">
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-lg-12 patient_option" align="center">
                        <h3>
                          Select an Existing Patient
                        </h3>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-6 col-md-offset-3 col-sm-4 col-sm-offset-4 patient_option" align="center">
                          <%= collection_select(:doctor, :patient_id, current_doctor.patients, :id, :name, {:include_blank => "Select Patient"},:class => "form-control", :name =>"existing_patient" ) %>
                      </div>
                    </div>
                    <div class="agree_btn_wrap" style="margin-right: 10px;">
                      <%= f.submit "Go to NEXT Step >>",:class=>"blue_btn agree_btn pull-right"%>
                      <%= link_to 'Cancel', patients_path, :class => "black_btn pull-right" %>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patient_report/_notice.html.erb
<%= flash[:notice] %>

app/views/patient_report/_patient_report_form.html.erb
<div id="content-header">
  <div id="breadcrumb">
    <%= link_to raw("<i class='icon-home'></i><span class='text'>Home</span>"),patients_path%>
    <%= link_to raw("<i class='icon-user'></i><span class='text'>Add Patient</span>"),new_patient_path%>
  </div>
</div>
<%= hidden_field_tag :response_action %>
<%= form_for @patient_report, :as => :patient, :url => report_for_patient_path, :html => { :method => :post,:multipart => true , :class=>"form-horizontal"}  do |f| %>
    <% if @patient_report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@patient_report.errors.count, "error") %> prohibited this patient from being saved:</h2>
        <ul>
        <% @patient_report.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <%end %>
    <center><div class="stp1">STEP-1 Add Patient</div></center>
    <div class="patient-form-border">
    <div class="row-fluid">
      <div class="span12">
        <div class="row-fluid">
          <div class="span6">
            <%= render "patients/controls1", :f => f %>
          </div>
          <div class="span6">
            <%= render "patients/controls2", :f => f %>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
      </div>
    </div>
    <div class="or"> OR </div>
    <div class="select-patient">Select an Existing Patient</div>
    <div class="row-fluid">
      <div class="span12">
        <center>
        <%= collection_select(:doctor, :patient_id, current_doctor.patients, :id, :name, {:include_blank => "Select Patient"},:class => "patient-dropdown-list", :name =>"existing_patient" ) %>
        </center>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">
      </div>
    </div>

    <div class="row-fluid">
       <div class="span12">
        <div class="button-goto">
          <%= link_to 'Cancel', patients_path, :class => "btn btn-inverse btn-large" %>
          <%= f.submit "Go to NEXT Step >>",:class=>"btn btn-success btn-large"%>
        </div>
      </div>
    </div>
<%end%>

app/views/patient_report/_patient_report_step1.html.erb
<div class="row">
    <div class="container">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 normal_tbl_wrap">
        <div class="dashboard_title">
          Add New Consent Presentation
          <span class="down_arrow">
            <img src="/assets/down_arrow_black.png" alt="">
          </span>
        </div>
        <div class="clearfix"></div>
        <div class="bs-example bs-example-tabs presentation_tabs_wrap">
          <div class="tab2">
            <div class="add-concent" >
              <div id="tabs">
                <ul class="nav nav-tabs custom_tabs" id="myTab">
                  <li class="active col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#add_patient">1. Add Patient</a></li>
                  <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#select_menu">2. Select Presentation Segment</a></li>
                  <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><a data-toggle="tab" href="#create_code">3. Create patient Code and Send</a></li>
                </ul>
                <div class="tab-content" id="myTabContent">
                  <div id="add_patient" class="tab-pane fade active in tab_content">
                    <div class="row tab_form">
                      <div class="tab-background">
                        <div class="stp1">
                          <%= render "patient_report/step1_form" %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
  </div>

app/views/patient_report/_step1_form.html.erb
<script type="text/javascript">
$(document).ready(function(){
  if($('#dp6').length > 0)
  {
    $('#dp6').datepicker()
      .on('changeDate', function(ev){
        $('#dp6').datepicker('hide');
    });
  }
});
<%@patients = current_doctor.patients.all %>

$(document).ready(function(){
  $("#fname").blur(function(){
      var x = $("#fname").val();
      $(".symbol").removeClass('email_taken_no');
      $(".e_msg").hide();
      <% @patients.each do |value| %>
        if(x == "<%=value.email%>")
        {
          $(".symbol").addClass('email_taken_no');
          $(".e_msg").show();
          $("#fname").focus();
        }
      <% end %>
    });
});
</script>

<style>
  .email_taken_no{
    content: url(/assets/email_taken.png);
  }
</style>



<%= form_for @patient_report, :as => :patient, :url => report_for_patient_path,:remote=> true, :html => { :method => :post,:multipart => true}  do |f| %>
  <div class="add-concent-form">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="form-group form_wrap">
        <label for="fname">First name <em>*</em></label>
        <%= f.text_field :first_name , :placeholder => "First Name" , :class => "form-control"%>
      </div>
      <div class="form-group form_wrap">
        <label for="fname">Last name <em>*</em></label>
        <%= f.text_field :last_name , :placeholder => "Last Name", :class => "form-control" %>
      </div>
      <div class="row">
        <div class="form-group form_wrap">
          <label for="Gender">Gender <em>*</em></label>
          <div class="row">
            <div class="col-lg-2" style="padding-left:0;">
              <div class="radio">
                <label>
                  <%=f.radio_button :gender , "Male"%>Male
                </label>
              </div>
            </div>
            <div class="col-lg-2" style="padding-left:0;">
              <div class="radio">
                <label>
                 <%=f.radio_button :gender, "Female"%>Female
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group form_wrap">
        <label for="email">Email <em>*</em></label>
        <%= f.email_field :email,:placeholder => "Email", :class => "form-control",:id=>"fname" %>
        <span class="symbol" style="margin-bottom:-8px;"> </span>
        <span class="e_msg" style="display:none;  color:#ff0000;">This patient is already in your list.</span>
      </div>
      <div class="form-group form_wrap">
        <label for="email">Phone <em>*</em></label>
        <%= f.hidden_field :phone_code,:placeholder => "Code", :class => "code"%>
        <%= f.text_field :phone_number,:placeholder => "Number", :class => "form-control"%>
      </div>
      <div class="form-group form_wrap">
        <label for="bday">Birthdate <em>*</em></label>
         <%= f.text_field :birthdate,:placeholder => "Enter Date of Birth", :id => "dp6" ,:class=>"form-control",:"data-date"=>"07/22/2013",:"data-date-format"=>"dd/mm/yyyy"%>
      </div>
     </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="form-group form_wrap">
        <label for="email">Address / suite<em>*</em></label>
        <%= f.text_area :address, :placeholder => "Address",:class => "form-control",:rows => 5, :cols => 50  %>
      </div>
      <div class="form-group form_wrap">
        <label for="bday">City <em>*</em></label>
         <%= f.text_field :city, :placeholder => "City", :class => "form-control" %>
      </div>
      <div class="form-group form_wrap">
        <label for="bday">State <em>*</em></label>
        <%= f.text_field :state,:placeholder => "State", :class => "form-control" %>
      </div>
      <div class="form-group form_wrap">
        <label for="bday">Country <em>*</em></label>
        <%= f.country_select :country,{priority: %w(US)}, :placeholder => "Country",:class=>"form-control"%>
      </div>
      <div class="form-group form_wrap">
        <label for="bday">Zip <em>*</em></label>
        <%= f.text_field :zip, :placeholder => "Zip", :class => "form-control" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-lg-12 form_devider" align="center">
        <img src="/assets/or_img.png" class="img-responsive">
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 patient_option" align="center">
        <h3>
          Select an Existing Patient
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-4 col-sm-offset-4 patient_option" align="center">
          <%= collection_select(:doctor, :patient_id, current_doctor.patients, :id, :name, {:include_blank => "Select Patient"},:class => "form-control", :name =>"existing_patient" ) %>
      </div>
    </div>
    <div class="agree_btn_wrap" style="margin-right: 10px;">
      <%= f.submit "Go to NEXT Step >>",:class=>"blue_btn agree_btn pull-right"%>
      <%= link_to 'Cancel', patients_path, :class => "black_btn pull-right" %>
    </div>
  </div>
<%end%>

app/views/patient_report/create.js.erb
<% if params[:existing_patient].present? %>

   $('#tabs').remove();
        $('.add-concent').html("<%= escape_javascript(render :partial => 'patients/consent_report', :locals => {:patient_report => @patient_report}).html_safe %>");
        resizeWindow();
      function resizeWindow()
      {

          if(document.documentElement.scrollHeight - document.documentElement.clientHeight>0)
              footer.css("position","relative");
          else
          {
              footer.css("position","fixed");
              footer.css("bottom","0px");
          }
      }

<% else %>

  <% if @patient_report.errors.count == 0 %>

    $('#tabs').remove();
    $('.add-concent').html("<%= escape_javascript(render :partial => 'patients/consent_report', :locals => {:patient_report => @patient_report}).html_safe %>");
    resizeWindow();
    function resizeWindow()
    {
      if(document.documentElement.scrollHeight - document.documentElement.clientHeight>0)
          footer.css("position","relative");
      else
      {
          footer.css("position","fixed");
          footer.css("bottom","0px");
      }
    }

  <% else %>

    $('.stp1').hide();
    $('.tab-background').html("<%= escape_javascript(render :partial => 'patient_report/step1_form').html_safe %>");
  <% end %>
<% end %>

app/views/patient_report/edit.js.erb
$('#tabs2').remove();
$('.add-concent').html("<%= escape_javascript(render :partial => 'patient_report/edit_patient_report', :locals => {:patient_report => @patient_report}).html_safe %>");
resizeWindow();
function resizeWindow()
    {
        if(document.documentElement.scrollHeight - document.documentElement.clientHeight>0)
            footer.css("position","relative");
        else
        {
            footer.css("position","fixed");
            footer.css("bottom","0px");
        }
    }

app/views/patient_report/new.html.erb
<%= render "patient_report/patient_report_step1"%>

app/views/patient_report/new.js.erb
alert("ERROR");

app/views/patient_report/update.js.erb
$('#tabs').remove();
$('.add-concent').html("<%= escape_javascript(render :partial => 'patients/consent_report', :locals => {:patient_report => @patient_report}).html_safe %>");
resizeWindow();
function resizeWindow()
{
	if(document.documentElement.scrollHeight - document.documentElement.clientHeight>0)
		footer.css("position","relative");
	else
	{
		footer.css("position","fixed");
		footer.css("bottom","0px");
	}
}