config/routes.rb
Consent::Application.routes.draw do

  resources :subscribers, only: [:new, :create]
  resources :contact_us
  resources :patients_testimonials
  resources :doctors_testimonials
  resources :report_questions, :only => [:new, :create, :destroy]

  match "report_questions/reply",:to => "report_questions#reply",:via=> [:get]
  match ":id/report_questions",:to => "report_questions#index",:as=>:report_questions,:via=> [:get]

  match "report_questions/:id",:to => "report_menus#show",:as=>:report_question,:via=> [:get]

  match ":id/report_questions",:to => "report_questions#create",:as=>:report_questions,:via=> [:post]

  authenticated :doctor do
    root :to => 'patients#index'
  end

  match "/admin/active_doctors" => 'admin/doctors#active_doctors', via: :get, as: "active_doctors"
  match "/admin/non-active-doctors" => 'admin/doctors#non_active_doctors', via: :get, as: "non_active_doctors"
  match "/admin/cancel-trial/:id" => 'admin/doctors#admin_cancel_trials', via: :get, as: "admin_cancel_trials"

  authenticated :patient do
    root :to => 'patients#patient_info'
  end

  root :to => "home#index"

  match '/patients/get_emails', :to => "patients#get_emails", :as => :get_emails
  resources :patients
  devise_for :patients, :controllers => { :sessions => "sessions"}, :path => "patient", :path_names => { :sign_in => "login" } do
    match '/patients/signin/:token', :to => 'sessions#new', :as => 'signin_patient', :via => [:get]
  end

  resources :report_menus,:only => [ :create, :new, :update, :edit ]
  match '/report_menus/new/:id' , :to => 'report_menus#new' ,:as => :new_report,:via => [ :get ]

  match "embeddocusign/create" =>"embeddocusign#create", :as => :embeddocusign_create

  resources :videos, :only => [:index, :show]

  resources :user_steps
  get "doctor_profile/index"
  get "doctor_profile/edit"
  get "doctor_profile/update"
  get "patient_report/new"
  get "patient_report/create"

  get '/report/download_as_pdf/:id',:to =>"reports#download_as_pdf",:as=> :download_as_pdf

  match '/update_consent_report/:id' => "patients#update_consent_report", :as => :update_consent_report

  resources :patient_report
  match 'patient_report/new', :controller => 'patient_report', :action => 'create', :as => :report_for_patient
  match 'profile' => "doctor_profile#edit", :as => :profile
  match 'profile/edit' => "doctor_profile#update", :via => [ :put ], :as => :update_profile
  match "/doctor/cancel-trial/:id" => 'doctor_profile#doctor_cancel_trials', via: :get, as: "doctor_cancel_trials"

  match 'patient/patient_info' => "patient#patient_info", :via => [ :get ]
  match '/consent_report/:id' => "patients#consent_report",:as => :consent_report
  match '/create_report/:id' => "patients#create_report", :as => :create_report
  match '/edit_consent_report/:id' => "patients#edit_consent_report", :as => :edit_consent_report
  match '/patients/show_code', :to => "patients#show_code", :as => :show_code
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan

  match '/reports/access_report', :to => "reports#access_report", :as => :access_report
  match '/reports/access_rep/:id', :to => "reports#access_rep", :as => :access_rep
  match '/reports/show_report', :to => "reports#show_report" , :as => :show_report
  match ':id/login_page', :to => "reports#login_page" , :as => :login_page
  match '/reports/send_mail/:id', :to => "reports#send_mail", :as => :send_mail
  match '/reports/past_report',:to => "reports#past_report", :as => :past_report
  match '/reports/view_report/:id',:to => "reports#view_report",:as => :view_report
  match '/reports/:id/website_desclaimer',:to =>"reports#website_desclaimer",:as=> :website_desclaimer
  get '/reports/:id/pat_report',:to =>"reports#pat_report",:as=> :pat_report

  get '/reports/signature_created_msg',:to=>"reports#signature_created_msg",:as=> :signature_created_msg
  match '/:id/edit' => "confirm_detail#edit", :as => :edit
  match '/update/:id' => "confirm_detail#update", :as => :update
  match '/show/:id' => "confirm_detail#show",:as => :show

  match '/reports/:id/i_do_not_agree', :to => "reports#i_do_not_agree", :as => :i_do_not_agree
  match '/patient/patient_update' => "patient#pat_update", :as => :pat_update
  match 'home/terms_condition' => "home#terms_condition"

  resources :payments, :only => [:new,  :create]
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/select_plan', :to => 'payments#select_plan', :as => 'select_plan'
  match '/payments/plan_detail', :to => 'payments#plan_detail', :as => 'plan_detail'
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan
  post 'payments/webhook'

  resources :photos

  get '/home/coming_soon',:to =>'home#coming_soon'
  get '/home/contact_us',:to =>'home#contact_us'

  match '/home/services' =>'home#services', :as => :services
  match '/home/about_us' =>'home#about_us', :as => :about_us
  match '/home/contact_us' =>'home#contact_us', :as => :contact_us
  match '/home/contact_us_submit', :to => "home#contact_us_submit", :as => :contact_us_submit
  match '/home/how_it_works' =>'home#how_it_works', :as => :how_it_works

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :doctors, :controllers => { :registrations => "registrations", :sessions => "sessions",:passwords => "passwords" } do
     get '/doctors/sign_out' => 'devise/sessions#destroy'
     get '/doctors/sign_in' => 'devise/sessions#new'
  end

    match "embeddocusign/create_template" =>"embeddocusign#create_template", :as => :embeddocusign_create_template
    match "embeddocusign/create_envelope_from_template" =>"embeddocusign#create_envelope_from_template", :as => :create_envelope_from_template
    match "embeddocusign/create_env_from_doc/:id" =>"embeddocusign#create_env_from_doc", :as => :create_env_from_doc
    match "embeddocusign/generate_pdf/:id" =>"embeddocusign#generate_pdf", :as => :generate_pdf

  namespace "admin" do
    resources :doctors do
      get :pat_show
    end
    resources :patients do
      get :show_patient_reports
    end
    resources :procedures do
      get :procedure_show_type
    end
    resources :procedure_types do
      get :sub_type
    end
  end

  namespace "admin" do
    resources :videos do
      post :change_procedure
      new do
        post :upload
        get  :save_video
      end
    end
    resources :photos
  end

  match '/admin/videos/change_procedure', :to => "admin/videos#change_procedure"
  match '/admin/procedure_types/:id/create_subtype', :to => "admin/procedure_types#create_subtype" ,:as => 'create_subtype'

  match 'signature_pads/:id' => "signature_pads#open_form", :as => :open_form
  match 'send_mail/:id' => "signature_pads#send_mail", :as => :send_mail_pad

  match  'report/signature_create/:id'=> "reports#signature_create", :as => :signature_create
  match '/signatures/:id' => "reports#sig_create",:as => :sig_create
  match '/thnkyou_msg' => "reports#thnkyou_msg",:as => :thnkyou_msg

 if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  ActiveAdmin.routes(self)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_filter :authenticate_doctor!
  def index
    @doctors_testimonials = DoctorsTestimonial.find_by_status(true)
    @doctors_testimonials_last=DoctorsTestimonial.limit(1).order('id desc')

    @patients_testimonials = PatientsTestimonial.find_by_status(true)
    @patients_testimonials_last=PatientsTestimonial.limit(1).order('id desc')
    if session[:subcribe_doc].present? && cookies[:free_plan].present?
      session[:subcribe_doc].update_attributes(:subscription_plan => "Free", :subscription_date => Time.now, :expire_date => Time.now + 30.days, :trial_expired => false, :trial_period => "30")
      DoctorMailer.delay(queue: "doctor-#{session[:subcribe_doc].id}", run_at: session[:subcribe_doc].expire_date.to_datetime - 7.days).trial_expired_notification(current_doctor)
      cookies.delete :free_plan
      sign_in(:doctor, session[:subcribe_doc])
      flash[:success]="Your free plan is activated now."
      redirect_to root_path
    end
  end

  def how_it_works

  end

  def coming_soon

  end

  def terms_condition

  end

  def services

  end

  def about_us

  end

  def contat_us
    
  end

  def contact_us_submit
    @contact_us = ContactUs.new(params[:contact_us])
    if @contact_us.save
      DoctorMailer.contact_us_notification(@contact_us).deliver
      flash[:notice] = "Successfully Submit."
      redirect_to contact_us_path
    end
  end

end
 

app/views/home/about_us.html.erb
<div class="row esignature_container">
    <div class="container">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="disclaimer_wrap esignature_box contact_box">
          <div class="disclaimer_title">
            ABOUT US 
            <span class="down_arrow">
              <img src="/assets/down_arrow.png" alt="">
            </span>
          </div>
          <div class="row about_box_wrap">
            <div class="col-lg-12">
              <p>Healthcare has become more involved and time consuming for the professional.  Quality care, patient expectations and legal requirement have continued to evolve into an ever heavier weight; dragging at the limited resources of the healthcare professional. </p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" align="center">
              <img src="/assets/about_img.jpg" alt="" class="img-responsive">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 about_sub_txt" align="center">
              <p>eInformedConsent.com makes a real positive difference in a healthcare practice.The doctor and the practice can reduce the risk of successful malpractice litigation.  For less than the cost of a premium cup of coffee daily the benefits of this system can be yours. eInformed Consent utilizes video, audio and pictures. The system adjust the presentation based on the proposed treatments.<br>
              Sooner or later every healthcare professional worries about informed consent.  Did I remember to explain this or talk about that?  Was I too rushed? Does the patient understand? How can I explain better without taking more time?  
              </p>
            </div>
          </div>
          <div class="row about_content">
            <div class="col-lg-12">
              <span>Did you know:</span>
              <ul>
                <li>19,000 malpractice payouts in 2012 – Source Annual Report, National Practitioner Data Bank, US DHHS</li>
                <li>Estimated 50-65% of doctors sued at least once in their career.</li>
                <li>Average cost to defend malpractice lawsuit $23,000.00 not counting payout or time spent -  malpractice statistics 2012</li>
              </ul>
              <div>eInformed Consent.com is a product of Consent Project LLC</div>
            </div>
          </div>
        </div>
      </div>
      <div class="agree_btn_wrap services_btns">
        <%= link_to "Subscribe Now", new_doctor_registration_path, :class=>"blue_btn pull-right agree_btn" %>
        <%= link_to  "Learn More",how_it_works_path,:class=>"black_btn pull-right" %>
      </div>
    </div>
  </div>

  

app/views/home/coming_soon.html.erb
<style type="text/css">
.fon_color{color: #5b5f63;}
</style>
<div class="wrapper">
  <section id="content">
    <br/>
  <h1 class = "fon_color">Coming Soon!</h1>
  <h2 class = "fon_color">The page you were looking for appears to have been Coming Soon.</h2>
  <ul>
    <%= image_tag "/assets/ComingSoon.jpg" %>
  </ul>

</section>
</div>

app/views/home/contact_us.html.erb
<div class="row esignature_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="disclaimer_wrap esignature_box contact_box">
        <div class="disclaimer_title">
          Contact Us
          <span class="down_arrow">
            <img src="/assets/down_arrow.png" alt="">
          </span>
        </div>
        <%= form_for :contact_us, :url => contact_us_submit_path,:method => 'POST',:html => {:class=>"form signup_form",:id => "contact_us"}  do |f|%>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-group form_wrap">
                  <label for="name">name <em>*</em></label>
                  <%= f.text_field :name,:class=>"form-control",:placeholder=>"Name",:required => true %>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                  <div class="form-group form_wrap">
                    <label for="email">Email <em>*</em></label>
                    <%= f.text_field :email,:class=>"form-control",:placeholder=>"Email", :id=>"email",:required => true%>
                  </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                  <div class="form-group form_wrap">
                    <label for="phone">Phone <em>*</em></label>
                    <%= f.text_field :phone,:class=>"form-control",:placeholder=>"Phone",:id=>"phone",:required => true  %>
                  </div>
                </div>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-group form_wrap">
                  <label for="comment">Comment <em>*</em></label>
                  <%= f.text_area :comment,:class=>"form-control",:placeholder=>"Comment", :required => true%>
                </div>
              </div>
              <div class="agree_btn_wrap contact_btn">
                <%= f.submit "Submit",:class=>"blue_btn pull-right agree_btn"%>
              </div>
            </div>
          <%end%>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "jquery.js","jquery.validate.js" %>
<script type="text/javascript">
  $("#contact_us").validate({
    rules: {
      "contact_us[email]": {
        required: true,
        email: true
      },
      "contact_us[phone]": {
        required: true,
        number: true
      }
    }
  });
</script>

app/views/home/how_it_works.html.erb
<div class="row how_word_wrap">
    <div class="container">
      <div class="col-lg-12">
        <img src="/assets/how_work_step.png" class="img-responsive">
        <a href="#" id="videocover" data-toggle="modal" data-target="#videoModal" data-backdrop="static" data-keyboard="false" class="view_demo hidden-xs">
          <img src="/assets/view_btn.png" class="view_demo hidden-xs">
        </a>
      </div>
    </div>
  </div>

  <div class="row esignature_container">
    <div class="container">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <a href="#" id="videocover" data-toggle="modal" data-target="#videoModal" class="btn btn-primary btn-lg btn-block hidden-sm hidden-md hidden-lg" style="margin-top: 10px;">View Demo</a>
        <div class="disclaimer_wrap esignature_box contact_box">
          <div class="disclaimer_title">
            See how easy it is to use eInformedConsent.com
            <span class="down_arrow">
              <img src="/assets/down_arrow.png" alt="">
            </span>
          </div>

          <div class="how_work_content">
            <div>
              <span>1</span>
              Subscription by doctor
              <p>Get started by registering your information and select your subscription plan, one time. Create your login ID</p>
            </div>
            <div>
              <span>2</span>
              Setup Patient Presentation
              <p>Create a patient presentation anytime by completing a patient’s demographic information, selecting their presentation segments. This will in turn create a Unique Patient Code, which is sent via email to the patient and to you as a patient handout</p>
            </div>
            <div>
              <span>3</span>
              Your Patient logs into their presentation with Unique Patient Code
              <p>Patient will log onto the website using a Unique Patient Code and The Patient will see a presentation selected by the doctor</p>
            </div>
            <div>
              <span>4</span>
              Doctor receives a report advising that the patient has completed the presentation
              <p>The doctor is sent a report tracking the patient’s interaction with their presentation and the patient’s questions. The system maintains a historical copy of all reports</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<%= render :partial => "/layouts/shared/how_it_works_video" %>

<style type="text/css">
  .view_demo {
    font-size: 18px;
    border-radius: 6px;
    float: left;
    position: absolute;
    left: 59%;
    top: 44%;
    color: #fff;
    margin: -25px 0 0 -112px;
  }
  .view_demo:hover {
    color: #fff;
  }
  .img-responsive { position: relative; }

  @media (max-width: 768px) {
    .view_demo {
      padding: 10px 30px 10px !important ;
      margin: -20px 0 0 -90px !important;
    }
  }

  @media (max-width: 640px) {
    .view_demo {
      padding: 5px 15px !important ;
      margin: -20px 0 0 -70px !important;
    }
  }


  @media (max-width: 480px) {
    .view_demo {
      padding: 3px 10px !important ;
      margin: -20px 0 0 -70px !important;
    }
  }
</style>

app/views/home/index.html.erb
<%= render "/home/shared/front_page_photo_slider"%>
<%= render "/home/shared/front_page_home_page_content"%>

app/views/home/services.html.erb
<div class="row esignature_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="disclaimer_wrap esignature_box contact_box">
        <div class="disclaimer_title">
          Services
          <span class="down_arrow">
            <img src="/assets/down_arrow.png" alt="">
          </span>
        </div>
        <div class="row service_box_wrap">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Allows the patient to gain understanding of proposed treatments and alternatives from:
            <ul>
              <li>Home</li>
              <li>Work</li>
              <li>Your office</li>
            </ul>
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Makes presentations to
            <ul>
              <li>Personal computers </li>
              <li>Tablets </li>
              <li>Smart phones.</li>
            </ul>
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Your Patients
            <ul>
              <li>See pleasant videos on their proposed treatments </li>
              <li>Get valuable information on alternative treatments</li>
              <li>Gain comprehension regarding possible complications</li>
              <li>Learn about their responsibilities for successful treatment.</li>
              <li>They can watch, replay, ask questions and acknowledge they understand.</li>
            </ul>
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Provides reports to the practice along with third party verification on:
            <ul>
              <li>Patient’s acknowledged understanding</li>
              <li>Time spent learning about their situation</li>
              <li>The patient’s consent to proceed with treatment.</li>
            </ul>
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Stores a permanent record of the presentation reports, which include:
            <ul>
              <li>What was presented </li>
              <li>How it was presented</li>
              <li>Time spent on the presentation</li>
              <li>Patient questions to the healthcare professional</li>
            </ul>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="disclaimer_title">
          Benefits
          <span class="down_arrow">
            <img src="/assets/down_arrow.png" alt="">
          </span>
        </div>
        <div class="row service_box_wrap">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Saves healthcare professional time.
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Significantly reduces healthcare professional risk.
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Enhances professional image of the healthcare professional
          </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 service_box">
            Lowers healthcare professional costs while increasing value.
          </div>
        </div>
    </div>
    <div class="agree_btn_wrap services_btns">
      <input type="button" value="Learn More" class="blue_btn pull-right agree_btn">
      <!-- <input type="button" value="Subscribe Now" class="black_btn pull-right"> -->
      <%= link_to "Subscribe Now", new_doctor_registration_path, :class=>"black_btn pull-right" %>
    </div>
  </div>
</div>
</div>