config/routes.rb
Consent::Application.routes.draw do

  resources :subscribers, only: [:new, :create]
  resources :contact_us
  resources :patients_testimonials
  resources :doctors_testimonials
  resources :report_questions, :only => [:new, :create, :destroy]

  match "report_questions/reply",:to => "report_questions#reply",:via=> [:get]
  match ":id/report_questions",:to => "report_questions#index",:as=>:report_questions,:via=> [:get]

  match "report_questions/:id",:to => "report_menus#show",:as=>:report_question,:via=> [:get]

  match ":id/report_questions",:to => "report_questions#create",:as=>:report_questions,:via=> [:post]

  authenticated :doctor do
    root :to => 'patients#index'
  end

  match "/admin/active_doctors" => 'admin/doctors#active_doctors', via: :get, as: "active_doctors"
  match "/admin/non-active-doctors" => 'admin/doctors#non_active_doctors', via: :get, as: "non_active_doctors"
  match "/admin/cancel-trial/:id" => 'admin/doctors#admin_cancel_trials', via: :get, as: "admin_cancel_trials"

  authenticated :patient do
    root :to => 'patients#patient_info'
  end

  root :to => "home#index"

  match '/patients/get_emails', :to => "patients#get_emails", :as => :get_emails
  resources :patients
  devise_for :patients, :controllers => { :sessions => "sessions"}, :path => "patient", :path_names => { :sign_in => "login" } do
    match '/patients/signin/:token', :to => 'sessions#new', :as => 'signin_patient', :via => [:get]
  end

  resources :report_menus,:only => [ :create, :new, :update, :edit ]
  match '/report_menus/new/:id' , :to => 'report_menus#new' ,:as => :new_report,:via => [ :get ]

  match "embeddocusign/create" =>"embeddocusign#create", :as => :embeddocusign_create

  resources :videos, :only => [:index, :show]

  resources :user_steps
  get "doctor_profile/index"
  get "doctor_profile/edit"
  get "doctor_profile/update"
  get "patient_report/new"
  get "patient_report/create"

  get '/report/download_as_pdf/:id',:to =>"reports#download_as_pdf",:as=> :download_as_pdf

  match '/update_consent_report/:id' => "patients#update_consent_report", :as => :update_consent_report

  resources :patient_report
  match 'patient_report/new', :controller => 'patient_report', :action => 'create', :as => :report_for_patient
  match 'profile' => "doctor_profile#edit", :as => :profile
  match 'profile/edit' => "doctor_profile#update", :via => [ :put ], :as => :update_profile
  match "/doctor/cancel-trial/:id" => 'doctor_profile#doctor_cancel_trials', via: :get, as: "doctor_cancel_trials"

  match 'patient/patient_info' => "patient#patient_info", :via => [ :get ]
  match '/consent_report/:id' => "patients#consent_report",:as => :consent_report
  match '/create_report/:id' => "patients#create_report", :as => :create_report
  match '/edit_consent_report/:id' => "patients#edit_consent_report", :as => :edit_consent_report
  match '/patients/show_code', :to => "patients#show_code", :as => :show_code
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan

  match '/reports/access_report', :to => "reports#access_report", :as => :access_report
  match '/reports/access_rep/:id', :to => "reports#access_rep", :as => :access_rep
  match '/reports/show_report', :to => "reports#show_report" , :as => :show_report
  match ':id/login_page', :to => "reports#login_page" , :as => :login_page
  match '/reports/send_mail/:id', :to => "reports#send_mail", :as => :send_mail
  match '/reports/past_report',:to => "reports#past_report", :as => :past_report
  match '/reports/view_report/:id',:to => "reports#view_report",:as => :view_report
  match '/reports/:id/website_desclaimer',:to =>"reports#website_desclaimer",:as=> :website_desclaimer
  get '/reports/:id/pat_report',:to =>"reports#pat_report",:as=> :pat_report

  get '/reports/signature_created_msg',:to=>"reports#signature_created_msg",:as=> :signature_created_msg
  match '/:id/edit' => "confirm_detail#edit", :as => :edit
  match '/update/:id' => "confirm_detail#update", :as => :update
  match '/show/:id' => "confirm_detail#show",:as => :show

  match '/reports/:id/i_do_not_agree', :to => "reports#i_do_not_agree", :as => :i_do_not_agree
  match '/patient/patient_update' => "patient#pat_update", :as => :pat_update
  match 'home/terms_condition' => "home#terms_condition"

  resources :payments, :only => [:new,  :create]
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/select_plan', :to => 'payments#select_plan', :as => 'select_plan'
  match '/payments/plan_detail', :to => 'payments#plan_detail', :as => 'plan_detail'
  match '/subscription/doctor_plan', :to => 'subscription#doctor_plan', :as => :doctor_plan
  post 'payments/webhook'

  resources :photos

  get '/home/coming_soon',:to =>'home#coming_soon'
  get '/home/contact_us',:to =>'home#contact_us'

  match '/home/services' =>'home#services', :as => :services
  match '/home/about_us' =>'home#about_us', :as => :about_us
  match '/home/contact_us' =>'home#contact_us', :as => :contact_us
  match '/home/contact_us_submit', :to => "home#contact_us_submit", :as => :contact_us_submit
  match '/home/how_it_works' =>'home#how_it_works', :as => :how_it_works

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :doctors, :controllers => { :registrations => "registrations", :sessions => "sessions",:passwords => "passwords" } do
     get '/doctors/sign_out' => 'devise/sessions#destroy'
     get '/doctors/sign_in' => 'devise/sessions#new'
  end

    match "embeddocusign/create_template" =>"embeddocusign#create_template", :as => :embeddocusign_create_template
    match "embeddocusign/create_envelope_from_template" =>"embeddocusign#create_envelope_from_template", :as => :create_envelope_from_template
    match "embeddocusign/create_env_from_doc/:id" =>"embeddocusign#create_env_from_doc", :as => :create_env_from_doc
    match "embeddocusign/generate_pdf/:id" =>"embeddocusign#generate_pdf", :as => :generate_pdf

  namespace "admin" do
    resources :doctors do
      get :pat_show
    end
    resources :patients do
      get :show_patient_reports
    end
    resources :procedures do
      get :procedure_show_type
    end
    resources :procedure_types do
      get :sub_type
    end
  end

  namespace "admin" do
    resources :videos do
      post :change_procedure
      new do
        post :upload
        get  :save_video
      end
    end
    resources :photos
  end

  match '/admin/videos/change_procedure', :to => "admin/videos#change_procedure"
  match '/admin/procedure_types/:id/create_subtype', :to => "admin/procedure_types#create_subtype" ,:as => 'create_subtype'

  match 'signature_pads/:id' => "signature_pads#open_form", :as => :open_form
  match 'send_mail/:id' => "signature_pads#send_mail", :as => :send_mail_pad

  match  'report/signature_create/:id'=> "reports#signature_create", :as => :signature_create
  match '/signatures/:id' => "reports#sig_create",:as => :sig_create
  match '/thnkyou_msg' => "reports#thnkyou_msg",:as => :thnkyou_msg

 if Rails.env.production?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  ActiveAdmin.routes(self)
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  attr_accessible :procedure_name, :procedure_description, :speciality_id
  validates :procedure_name, :speciality_id, :presence => true
  belongs_to :speciality
  #has_many :patients
  has_many :procedure_types
  has_many :report_menus
  has_many :videos, dependent: :destroy
  delegate :spe_name, :to => :speciality, :prefix => true

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :doctor_id,:patient_id,:signature,:connection_establish_time, :login_page_time_spent, :desclaimer_time_spent, :personal_info_confirmation_time_spent,:presentation_page_time_spent, :esignature_page_time_spent,:status,:econnection,:video_count

  belongs_to :doctor
  belongs_to :patient, :class_name => "Patient"
  has_many :report_menus


  delegate :first_name, :last_name, :email, :birthdate, :gender, :address, :city, :state, :country, :to => :patient, :prefix => true
  delegate :correct_first_name, :correct_last_name, :correct_birthdate, :correct_gender_number, :correct_address, :correct_city, :correct_state, :correct_country, :to => :patient, :prefix => true

  before_create :generate_token

  after_create :status_signature
  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end

  def status_signature
    self.status = "Pending"
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def login_page
    logger.info ">>>>>>>>>>>>>>>>login_page"
    session[:patient_id] = params[:id]
    session[:con_start]= Time.now
    session[:login_page]= Time.now
    logger.info "connection_establish:- >>>>>>>>>>>>>> #{session[:con_start]}"
  end

  def pat_report
    @patient = Patient.find(params[:id])
    @patient_reports = @patient.reports
  end

  def access_report
      logger.info ">>>>>>>>>>>>>>>> access_report"
      @report_code = params[:report_code].delete(' ')
      @report1 = Report.find_by_report_code(@report_code)

      if !params[:report_code].blank?
        if @report1 == nil
          flash[:notice] = "Sorry! you have entered invalid Patient Passcode.Try again."
          render :action =>'login_page'
        else
          if @report1.status == "Active"
            redirect_to signature_created_msg_path
          else
            @report1.update_attributes(:connection_establish_time => session[:con_start])
            redirect_to website_desclaimer_path(@report1)
          end
        end
      else
        flash[:notice] = "Sorry! you have entered invalid Patient Passcode.Try again."
        render :action =>'login_page'
      end
  end

  def send_mail
    @report = Report.find(params[:id])
    @patient = Patient.all
    @doctor = current_doctor
    @speciality = Speciality.find_by_id(@doctor.speciality_id)
    @speciality_doc = @speciality.spe_name.capitalize

    @patient.each do |pa|
      if pa.id == @report.patient_id
        @patient_report_f = pa.first_name
        @patient_report_l = pa.last_name
        if pa.gender.to_s == "Male"
          @patient_perticuler = "He"
        else
          @patient_perticuler = "She"
        end
      end
    end

    PatientMailer.registration_confirmation(@report,@doctor,@speciality_doc).deliver
    DoctorMailer.patient_registration_confirmation(@report,@doctor,@speciality_doc,@patient_report_f,@patient_report_l,@patient_perticuler).deliver

    redirect_to root_url
    flash[:notice] = "Presentation has been successfully emailed"
  end

  def past_report
    @reports = current_doctor.reports.all
  end

  def view_report
    @report = Report.find(params[:id])
    @procedure_types = ProcedureType.all
    @report_menu = ReportMenu.all
  end

  def website_desclaimer
    @report = Report.find(params[:id])
    # cookies[:user_name] = @report.patient_first_name
    @report.update_attributes(:login_page_time_spent => session[:login_page])
    session[:website_des] = Time.now
    logger.info ">>>>>>>>>>#{session[:website_des]}>>>>>> website_desclaimer"
  end

  def i_do_not_agree
    logger.info ">>>>>>>>>>>>>>>> i_do_not_agree"
    @report = Report.find(params[:id])
    @patients = Patient.all
    @patients.each do |pa|
      if pa.id == @report.patient_id
        @patient = pa
      end
    end
    @doctors = Doctor.all
    @doctors.each do |doc|
      if doc.id == @report.doctor_id
        @doctor = doc
        @speciality = Speciality.find_by_id(@doctor.speciality_id)
        @speciality_doc = @speciality.spe_name.capitalize
      end
    end
    PatientMailer.thank_you_message(@report,@patient,@doctor,@speciality_doc).deliver
    DoctorMailer.dont_agee_notification(@report,@patient,@doctor,@speciality_doc).deliver
    logger.info ">>>>>>>>>>> #{@report.id} <<<<<<<"
  end

  def access_rep
    # @report = Report.find(params[:id])
    # w = @report.login_page_time_spent
    # e = session[:website_des]
    # @drr = w - e
    # logger.info "Difference------> #{@drr}"
    session[:personal_info]= Time.now
    @report = Report.find(params[:id])
    @report.update_attributes(:desclaimer_time_spent => session[:website_des])
    session[:report] = @report.id
  end

  def signature_create
    @report = Report.find(params[:id])
    session[:signature_time] = Time.now
    @report.update_attributes(:presentation_page_time_spent => session[:question_page],:esignature_page_time_spent => session[:signature_time])
  end

  def sig_create
    session[:sig_create] = Time.now
    @signature = params[:report]
    @report = Report.find(params[:id])
    if !@signature.blank?
      @report.update_attributes(:econnection=>session[:sig_create])
      @report.update_attributes(:signature =>@signature[:signature],:status=>"Active")
    end

    if !@report.signature.blank?
      @presentations = Presentation.all
      @patients = Patient.all
      @doctors = Doctor.all
      @report_questions= ReportQuestion.all
      @report_menu = @report.report_menus.all
      @proce_type = ProcedureType.all

      @doctors.each do |doc|
        if doc.id == @report.doctor_id
          @doctor = doc
          @speciality = Speciality.find_by_id(@doctor.speciality_id)
          @speciality_doc = @speciality.spe_name.capitalize
        end
      end

      @patients.each do |pa|
        if pa.id == @report.patient_id
          @patient = pa
        end
      end

      ReportMailer.patient_report(@report,@doctor,@speciality_doc,@patient,@report_questions,@report_menu,@presentations).deliver
      # flash[:notice] = "Thank you for your time. Presentation is successfully reviewed."
      redirect_to  login_page_path(session[:patient_id])
    else
      @report.update_attributes(:signature =>@signature[:signature],:status=>"Pending")
      flash[:notice] = 'Please provide your signature.'
      render :action =>'signature_create'
    end
  end

  def thnkyou_msg

  end

  def download_as_pdf
    @presentations = Presentation.all
    @report = Report.find(params[:id])
    @patients = Patient.all
    @doctors = Doctor.all
    @report_questions= ReportQuestion.all
    @report_menu = @report.report_menus.all
    @proce_type = ProcedureType.all

    @doctors.each do |doc|
      if doc.id == @report.doctor_id
        @doctor = doc
        @speciality = Speciality.find_by_id(@doctor.speciality_id)
        @speciality_doc = @speciality.spe_name.capitalize
      end
    end
    @patients.each do |pa|
      if pa.id == @report.patient_id
        @patient = pa
      end
    end
    pdf = ReportPdf.new(@report,@doctor,@speciality_doc,@patient,@report_questions,@report_menu,@presentations)
    send_data pdf.render, :filename => "#{@patient.first_name} #{@patient.last_name} #{@report.created_at.strftime("%d %B %Y")}.pdf", :type => "application/pdf"
  end

  def signature_created_msg
  end

end

app/views/reports/access_rep.html.erb
<div class="ajax">
  <div class="row patient_info_container">
    <div class="container">
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 patient_info_left">
        Please review the following information,
        make changes if necessary and acknowledge
        the information is correct.
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 patient_info_right">
        <div class="patient_info_box">
          <div class=" patient_info_title">Patient Details</div>
          <div class="patient_info_box">
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Patient Name :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none">
                  <span><%= @report.patient.first_name.capitalize %> <%= @report.patient.last_name.capitalize %></span>
                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Date of Birth :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none">
                  <% if !@report.patient.birthdate.blank? %>
                    <span><%= @report.patient.birthdate.strftime("%b %d, %Y") %></span>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Gender :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none">
                  <span><%= @report.patient.gender %></span>
                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Address :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none">
                  <span>
                    <%= @report.patient.address %>. <br>
                    <%= @report.patient.city %>,<br>
                    <%= @report.patient.state %>, <%= @report.patient.zip %>.
                  </span>
                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Phone :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none">
                  <span><%= @report.patient.phone_number %></span>
                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5">
                  Email :
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-7 p-left-none truncate marquee">
                <span title="<%= @report.patient.email %>"><%= @report.patient.email %></span>

                </div>
              </div>
            </div>
            <div class="patient_info_line">
              <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12" align="center">
                  <%= button_to "Edit Details",edit_path(@report.patient_id) ,:class=>"black_btn",:remote=>true%>
                </div>

                  <% @report_menu = @report.report_menus.sort %>
                  <% @report_menu.length %>
                  <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12" align="center">
                    <%#= link_to "Confirm and Continue", report_question_path(@report_menu.first.id, :q => @report_menu.first.query_str) ,:class=>"blue_btn" %>
                    <%= button_to "Confirm and Continue",report_questions_path(@report_menu.first.id), :method=>:get ,:class=>"blue_btn"%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="demo"></div>
<%= render "layouts/shared/login_jquery"%>

app/views/reports/access_report.html.erb
<div class="access_report">
<div class="ex1"><p class="leg">Patient Information<p></div>
  <div class="right-patient-info"><div class="add">Patient Name : <%= @report.patient_first_name %> <%= @report.patient_last_name %></div><br />
    <div class="gen-date">Date Of Birth : <%= @report.patient_birthdate.strftime("%b %d, %Y") %><br />
    Gender : <%= @report.patient_gender %><br /></div>
  </div>
  <div class="left-patient-info">
    <div class="add1">Address</div><br /><br/>
    <div class="add2"><%= @report.patient_address %>,</div><br />
    <div class="city"><%= @report.patient_city %>,</div><br />
    <div class="state"><%= @report.patient_state %>,</div><br />
    <div class="country"><%= @report.patient_country %></div><br />
  </div>
  <center> <%= button_to "Edit Details",edit_path(@report.patient_id) ,:class=>"gray-btn custom-btn",:remote=>true%>
                <%= button_to "Confirm and Continue",report_questions_path, :method=>:get ,:class=>"blue-btn custom-btn"%></center>
</div>
<%= render "layouts/shared/login_jquery"%>

app/views/reports/i_do_not_agree.html.erb
<div class="row confirmation_msg_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <!-- Button trigger modal -->
      <div align="center">
        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" style="margin-top:15%;">
          Click on me!
        </button>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Thank You!</h4>
          </div>
          <div class="modal-body">
            Thank you from Visiting eInformedConsent.com.  We will let your doctor know you decided not see the presentation.
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
          </div>
        </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>
  </div>
</div>

app/views/reports/login_page.html.erb
<div class="row user_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="patient_login_box">
        <h1>Patient Login</h1>
        <p>Please Enter Patient Passcode provided<br>by Your Doctor.</p>
        <%= form_for :report, :url => access_report_path, :method => 'POST',:class=>"form" do %>
          <div class="form-group form_wrap">
            <%= text_field_tag :report_code,"",:class=>"form-control",:placeholder=>"Enter Patient Passcode Here"  %>
          </div>
          <div class="form-group form_wrap">
            <input type="button" class="form-control pull-left login_leave_btn" value="Leave" onclick="window.location='/'">
            <%= submit_tag "Go",:class=>"form-control pull-right login_go_btn"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reports/signature_create.html.erb
<script>
function myFunction()
{
  var a = $('#ip').val();
  $('#op').html(a);
  $("#error").hide();
}
$( document ).ready(function() {

  if($('#ip').val() ==  "")
    $('#submitButton').attr('disabled', true);
    $("#error").show('slow');


  $('#ip').keyup(function(){

    if($('#ip').val() !=  "")
      $('#submitButton').attr('disabled', false);

    else
      $("#error").show('slow');
  });
});
</script>
  <%= form_for :report, url: sig_create_path(@report) ,:html => {:class => "form"} do |f| %>
<div class="row esignature_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="disclaimer_wrap esignature_box">
        <div class="disclaimer_title">
          E-Signature
          <span class="down_arrow">
            <img src="/assets/down_arrow.png" alt="">
          </span>
        </div>

        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 esignature_title">
            I understand the proposed treatment and considered the possible alternative treatment. I consent to proceed with the treatment Dr.  <%= @report.doctor.doctor_name.titleize %> has proposed for me.
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 signature_img" align="center">
            <img src="/assets/signature_img.png" alt="" class="img-responsive">
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

              <div class="form-group form_wrap">
                <div class="checkbox esignature_chkbox">
                  <label>
                    Please provide your E-Signature here.
                  </label>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                  <div class="form-group form_wrap">
                    <div class="form-group">
                      <%= f.text_field :signature,:class=>"form-control signature_txtbox", :align=>"bottom", :placeholder=>"Type Your Signature Here",:id=>"ip",:onkeyup=>"myFunction();"%>
                      <div id="error" style="color:red; display:none">Enter Your Signature</div>
                    </div>

                  </div>
                </div>

                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                  <div class="form-group form_wrap sign_preview_wrap">
                    <label>Drawn Signature</label>
                    <div class="clearfix"></div>
                    <div class="sign_preview" id="op" align="center">
                      <%= @report.signature %>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-lg-12 sign_btns">
                  <% @report_menu = @report.report_menus.sort %>
                  <% @report_menu.length %>
                   <input type="submit" class="blue_btn" value="Exit" data-toggle="modal" data-target="#myModal", id="submitButton">
                    <%= link_to  "Back",report_questions_path(@report_menu.first.id),:class=>"black_btn"%>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


 <!-- <div class="row confirmation_msg_container">
  <div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <!-- Button trigger modal -->
     <!--  <div align="center">

      </div> -->

      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
          <%# if @report.signature.blank?%>
            <div class="modal-header">
            <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> -->
            <h4 class="modal-title" id="myModalLabel">Thank You!</h4>
            </div>
            <div class="modal-body">
              Thank you for Visiting eInformedConsent.com. We will let your doctor know that you have successfully completed the Presentation.
            </div>
            <div class="modal-footer">
              <%= f.submit "Okay",:class=>"btn btn-primary" %>
            <%#= link_to "Okay", login_page_path(session[:patient_id]),:class=>"btn btn-primary"%>
            </div>
          <%# else%>

        </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    <!-- </div>
  </div>
</div> -->
 <% end %>
<%= render "layouts/shared/login_jquery"%>

app/views/reports/view_report.html.erb
<div id="content-header">
  <div id="breadcrumb">
    <%= link_to raw("<i class='icon-home'></i><span class='text'>Home</span>"),patients_path%>
    <%= link_to raw("<i class='icon-tasks'></i><span class='text'>Show Patient Report</span>"),view_report_path%>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <div class="widget-box">
        <div class="widget-title">
          <span class="icon">
            <i class="icon-eye-open"></i>
          </span>
          <h5>Patient Report</h5>
        </div>
        <div class="widget-content nopadding">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td><b>First name:</b></td>
                <td><%= @report.patient_first_name %></td>
              </tr>
              <tr>
                <td><b>Last name:</b></td>
                <td><%= @report.patient_last_name %></td>
              </tr>
              <tr>
                <td><b>Email:</b></td>
                <td><%= @report.patient_email %></td>
              </tr>
              <tr>
                <td><b>Gender:</b></td>
                <td><%= @report.patient_gender %></td>
              </tr>
              <tr>
                <td><b>Selections:</b></td>
                <% @report_menu.each do |menu| %>
                  <% if @report.id == menu.report_id %>
                    <% @procedure_types.each do |p| %>
                      <% if p.id == menu.procedure_type_ids %>
                        <% if p.parent_type_id == nil%>
                          <td><%= p.type_name %></td>
                        <% else %>
                          <td><%= p.type_name %></td>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>